name: gen AI
description: Interagindo com a AI
title: "Envie uma mensagem"
labels: ["IA", "Hello World"]

body:
  - type: markdown
    attributes:
      value: |
        Use a imaginação
  - type: input
    id: prompt
    attributes:
      label: ">>prompt<<"
      description: Envie uma mensagem ao gemini
      placeholder: Ola, como vai você hoje?
      label: ">>teste_123<<"
      description: Envie uma mensagem ao gemini
      placeholder: Ola, como vai você hoje?
    validations:
      required: true