name: gen AI
description: Deixe a AI criar um hello-world-workflow com a linguagem escolhida
title: "Criar uma pipeline de hello world"
labels: ["IA", "Hello World"]

body:
  - type: markdown
    attributes:
      value: |
        Adicione aqui a linguagem
  - type: input
    id: linguagem
    attributes:
      label: ">>linguagem<<"
      description: Escolha uma linguagem de programação
      placeholder: python
    validations:
      required: true
  - type: input
    id: extra
    attributes:
      label: ">>funcionalidade_extra<<"
      description: Tem uma ideia a mais?
      placeholder: mostrar data atual
    validations:
      required: false