name: criar hello world

on:
  issues:
    types: [opened, reopened]

jobs:
  issue-to-json:
    name: Convert issue body to json
    if: contains(github.event.issue.body, '>>linguagem<<')
    runs-on: ubuntu-latest
    outputs:
      payload-parsed: ${{ steps.payload.outputs.json_var }}
    steps:
      - name: Run parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'
      - name: Set Output
        id: payload
        run: echo json_var='${{ steps.parse.outputs.payload }}' >> $GITHUB_OUTPUT

  execute-pipe:
    name: criar hello world
    if: contains(github.event.issue.body, '>>linguagem<<')
    runs-on: ubuntu-latest
    needs: issue-to-json
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        #### Important, in case main branch is protected (for direct commits) it has to checkout in a valid branch
        ### In this case, change below
        #with:
        #  ref: '<branch_name>'
     
      - name: 'code add'
        id: status
        continue-on-error: true
        env:
          linguagem: ${{ fromJson(needs.issue-to-json.outputs.payload-parsed)['linguagem'] }}
        run: echo ${linguagem}

      - name: 'Comment code'
        if: steps.status.outcome == 'success'
        uses: peter-evans/close-issue@v2
        with:
          close-reason: not_planned
          comment: |
            **This is your verification code**
            Copy and paste the following line in #member-registration channel:
            > /code ${{ steps.code.outputs.code_var }}
          labels: |
            code_send_to_user

      - name: "Commit changes"
        uses: EndBug/add-and-commit@v9
        if: steps.wait.outcome == 'success'
        with:
          message: new code
          committer_name: GitHub Actions
          committer_email: actions@github.com

      - name: 'Close issue: code added!'
        uses: peter-evans/close-issue@v2
        if: steps.status.outcome == 'success'
        with:
          comment: |
            Closing issue with success status
            Reason: code added
          labels: |
            pool_added
  